spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/powerlift?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: JoeriJanssen
    password: koelkast123
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 9085